### PR TITLE
Support PHP7.0

### PR DESCRIPTION
**Pull request by tgabi333**

### CODE REVIEW

**Comment by Nyholm** [comment]
Hm, I did not think that APC would be available in PHP7. As far as I know is APC build for php<5.5. If you are using php ~5.5 or php 7 you should use APCu. 
But I might be incorrect.

**Comment by tgabi333** [comment]
There is a BC layer for php7: http://php.net/manual/en/apcu.installation.php

**Comment by Nyholm** [comment]
Okey, did not know. Then we definitely need to support that.

**Comment by tgabi333** [comment]
My aim: there is a problem, that if i'd like to support php5, hhvm and php7, i have to stick to the old `apc` module, because hhvm only mimics support for `apc` api, and in php7 there is `apcu-bc`

**Comment by tgabi333** [comment]
@Nyholm do you have any idea whats the problem with the tests under php5?

**Comment by Nyholm** [comment]
Try fixing the integration tests to version 0.7.0.

**Comment by tgabi333** [comment]
Isn't it an apc bug?

`php -r "var_dump(apc_store('hello', 'h', 2)); sleep(4); var_dump(apc_exists('hello')); var_dump(apc_fetch('hello'));"`
outputs:

```
bool(true)
bool(true)
string(1) "h"
```

**Comment by Nyholm** [comment]
No, or... it is documented. Apc clears the cache before next request.

**Comment by tgabi333** [comment]
Cache persist between request, see: http://php.net/manual/en/function.apc-store.php

But my problem with that example above is when i set TTL to 2, and after four seconds i shouldn't get the value back since its expired.

**Comment by Nyholm** [comment]
That is an issue with the APC cache itself. I think you should skip that test.

**Comment by tgabi333** [comment]
https://github.com/krakjoe/apcu/issues/167

**Comment by tgabi333** [comment]
It seems there is a bug about negative ttl in apcu. i made a bypass, but i don't really like it :S

**Comment by tgabi333** [comment]
@Nyholm could you please take a look at it

**Comment by Nyholm** [comment]
I think it looks good but can I trouble you to make a PR to https://github.com/php-cache/cache

We have made this repo and many others read only. If I merge this here it will be overwritten.

**Pull request closed without merging**
